--- # start of the yaml
- name: install redis repos
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: enable redis package
  ansible.builtin.command: yum module enable redis:remi-6.2 -y

- name: install redis package
  ansible.builtin.yum:
    name: redis
    state: installed

- name: enable remote connections to redis
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: enable remote connections to redis
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable redis service
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes
... # end of the yaml