- name: install python
  ansible.builtin.yum:
    name: "{{item}}"
    state: installed
  loop:
  - python36
  - gcc
  - python3-devel

- name: app setup
  import_role:
    name: common
    tasks_from: app-setup

- name: install python dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: systemd setup
  import_role:
    name: common
    tasks_from: systemd-setup

