- name: user add
  ansible.builtin.command: id roboshop
  register: output
  ignore_errors: true

- when: output.rc != 0
  name: create user roboshop
  become: yes # sudo acces to create user
  ansible.builtin.user:
    name: roboshop
  
- name: create app direcotry
  ansible.builtin.stat:
    path: /app
  register: directory

- when: directory.stat.exists == False
  name: create app direcotry
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download {{component}} artifacts"
  ansible.builtin.get_url: 
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: extract {{component}} artifacts file
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes