- name: copy mongo.repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb shell
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load {{component}} data /  schema
  ansible.builtin.command: mongo --host mongodb.devopsbysatya.online < /app/schema/{{component}}.js